name: meeting  # Add your project name here  
description: A new Flutter project.  

publish_to: 'none' # Prevents the package from being published to pub.dev  

version: 1.0.0+1  

environment:  
  sdk: ">=2.19.0 <3.0.0"  

dependencies: 

  flutter:
    sdk: flutter
  shared_preferences: any
  path_provider: any
  flutter_tts: ^3.3.0
  firebase_core: ^3.12.0  
  flutter_local_notifications: any  
  geolocator: any  
  geofence_service: any  



flutter:  
  uses-material-design: true
  assets:
    - assets/images/login_background.jpg
    - assets/images/meeting_background.jpg
dev_dependencies:  
  flutter_lints: ^5.0.0  # Make sure to add it with an appropriate version

